# Generated by Django 3.2.6 on 2021-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('level', models.IntegerField()),
                ('region', models.CharField(choices=[('220', '220-هند'), ('360', '360-ایران'), ('560', '560-اروپا')], max_length=3)),
                ('rank', models.CharField(blank=True, max_length=300)),
                ('battle_pass', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
