# Generated by Django 3.2.6 on 2021-10-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('S', 'Sold')], max_length=1)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sell.account')),
            ],
        ),
    ]
