# Generated by Django 3.2.6 on 2021-10-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0002_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Account_Status',
        ),
    ]
