# Generated by Django 3.2.6 on 2021-10-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0003_auto_20211027_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(choices=[('220', '220-هند'), ('360', '360-ایران'), ('560', '560-اروپا')], default='360', max_length=3),
        ),
    ]
