# Generated by Django 3.2.6 on 2021-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0004_alter_account_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
