# Generated by Django 3.2.6 on 2021-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0005_auto_20211031_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='A', max_length=9),
        ),
    ]
