# Generated by Django 3.2.6 on 2021-11-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0006_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=9),
        ),
        migrations.CreateModel(
            name='AccountPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sell.account')),
            ],
        ),
    ]
