# Generated by Django 3.2.6 on 2021-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0007_auto_20211101_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='p_status',
            field=models.CharField(choices=[('w', 'Wait4Publish'), ('p', 'Published')], default='p', max_length=1),
        ),
    ]
