# Generated by Django 3.2.6 on 2021-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0008_account_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='w_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
