# Generated by Django 3.2.6 on 2021-11-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0009_auto_20211107_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='w_code',
        ),
    ]
