# Generated by Django 3.2.6 on 2021-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0010_remove_account_w_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='w_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
