# Generated by Django 3.2.6 on 2021-11-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0011_account_w_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='p_status',
        ),
    ]
