# Generated by Django 3.2.6 on 2021-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0012_remove_account_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='p_status',
            field=models.CharField(choices=[('w', 'Wait4Publish'), ('p', 'Published')], default='p', max_length=1),
        ),
    ]
