# Generated by Django 3.2.5 on 2021-12-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0013_account_p_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpictures',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountpictures',
            name='address',
        ),
        migrations.AddField(
            model_name='accountpictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Sell/pictures'),
        ),
    ]
