# Generated by Django 3.2.5 on 2021-12-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0014_auto_20211201_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpictures',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sell.account'),
        ),
    ]
