# Generated by Django 3.2.5 on 2021-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0015_accountpictures_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Sell/static/Sell/pictures'),
        ),
    ]
